version: '3'

services:
  api:
    image: back_node_app
    container_name: docker-node-app
    build: 
      context: .
      dockerfile: Dockerfile
    command: yarn start
    ports:
      - 5001:5001
    volumes: 
      - ./:/src
    environment:
      - PORT=5001
      - NODE_ENV=local
      - JWT_SECRET=${JWT_SECRET}
      - MYSQL_HOST=mysql_db 
      - MYSQL_USERNAME=username
      - MYSQL_PASSWORD=password
      - MYSQL_DATABASE=admin_app_api
      - MYSQL_DEBUG=true

    depends_on:
      - mysql
      
  mysql:
    image: mysql:8
    container_name: mysql_db
    command: --default-authentication-plugin=mysql_native_password
    restart: always
    ports:
      - 3308:3306
    environment:
      MYSQL_DATABASE: admin_app_api
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root